{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_file_safe_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe_release-1.0.aar",
          "url": "open_file_safe_release-1.0.aar",
          "size": 13898,
          "sha512": "47941ba798512657e98f33e3d13a3b54484c56df9cb9d738c954ac4d6ade46248e25b4cd3b424fc932c795d0613dfd605166c30c63e8b7c7b9362e3769b699fc",
          "sha256": "7c9d258dbd80b203c8e32ed007b139bbc25d4d1e9669dd270e013dbaa25fa50c",
          "sha1": "ec6fe1a7b7ae0322cc30bd6b1f9d76b0ae70116e",
          "md5": "263a4e024b837f246b6373108d4eb5cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe_release-1.0.aar",
          "url": "open_file_safe_release-1.0.aar",
          "size": 13898,
          "sha512": "47941ba798512657e98f33e3d13a3b54484c56df9cb9d738c954ac4d6ade46248e25b4cd3b424fc932c795d0613dfd605166c30c63e8b7c7b9362e3769b699fc",
          "sha256": "7c9d258dbd80b203c8e32ed007b139bbc25d4d1e9669dd270e013dbaa25fa50c",
          "sha1": "ec6fe1a7b7ae0322cc30bd6b1f9d76b0ae70116e",
          "md5": "263a4e024b837f246b6373108d4eb5cb"
        }
      ]
    }
  ]
}
