{
  "formatVersion": "1.1",
  "component": {
    "group": "com.syncfusion.flutter.pdfviewer",
    "module": "syncfusion_flutter_pdfviewer_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_debug-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_debug-1.0.aar",
          "size": 10587,
          "sha512": "1f2ccca89f3c5123a333ae9a192dfd847cd29fd69899d8c59d0137cec038313d157bf7da87288c3f888798b6fa247a4689516d16289a7ca77fa93d28ec19ac6a",
          "sha256": "c34f93016032c3ced1a43139a89b755192f3e19b437fb1afff96692750103a07",
          "sha1": "00409f3f3b9eb3127350c894e874f5d478345259",
          "md5": "936244ac49dcf298c81b28cf7d3ca777"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_debug-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_debug-1.0.aar",
          "size": 10587,
          "sha512": "1f2ccca89f3c5123a333ae9a192dfd847cd29fd69899d8c59d0137cec038313d157bf7da87288c3f888798b6fa247a4689516d16289a7ca77fa93d28ec19ac6a",
          "sha256": "c34f93016032c3ced1a43139a89b755192f3e19b437fb1afff96692750103a07",
          "sha1": "00409f3f3b9eb3127350c894e874f5d478345259",
          "md5": "936244ac49dcf298c81b28cf7d3ca777"
        }
      ]
    }
  ]
}
