{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 30046,
          "sha512": "34529c2b0ee4bbd5531cb107d0198b8bf880207fe573d5ec6614b5c522b71e83dbf675694456bd24e90f14e86a02c0db775e09e687741f1887f68ae618bdb4e6",
          "sha256": "6058cd6d8f4b2667976bb7acb1608a8f725c2ce761b4805636d5cbbc8b4a03a0",
          "sha1": "4335f6297768f2693bf8f9cf822e3b93484a1d14",
          "md5": "c4927b8710f63f4bd2f1e6c87360e899"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 30046,
          "sha512": "34529c2b0ee4bbd5531cb107d0198b8bf880207fe573d5ec6614b5c522b71e83dbf675694456bd24e90f14e86a02c0db775e09e687741f1887f68ae618bdb4e6",
          "sha256": "6058cd6d8f4b2667976bb7acb1608a8f725c2ce761b4805636d5cbbc8b4a03a0",
          "sha1": "4335f6297768f2693bf8f9cf822e3b93484a1d14",
          "md5": "c4927b8710f63f4bd2f1e6c87360e899"
        }
      ]
    }
  ]
}
