{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_profile-1.0.aar",
          "url": "local_auth_android_profile-1.0.aar",
          "size": 40481,
          "sha512": "61c23be8f7b7a36db65929a5b2ca5eb2b570ab182c3157afc62289c04bed8ed500c5b0b210bf70740d8a72d2baf95514cb9d2fa4d5ef3072d95b4700e78c7185",
          "sha256": "18ff02ffb33a42d3052819f0946dbac4aeb21d56dad52406ccb2aae891669d26",
          "sha1": "0e006c74b00d5bcc2930ddd6a62dc417c4115041",
          "md5": "136ffbc323518469cddf1cea271400df"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_profile-1.0.aar",
          "url": "local_auth_android_profile-1.0.aar",
          "size": 40481,
          "sha512": "61c23be8f7b7a36db65929a5b2ca5eb2b570ab182c3157afc62289c04bed8ed500c5b0b210bf70740d8a72d2baf95514cb9d2fa4d5ef3072d95b4700e78c7185",
          "sha256": "18ff02ffb33a42d3052819f0946dbac4aeb21d56dad52406ccb2aae891669d26",
          "sha1": "0e006c74b00d5bcc2930ddd6a62dc417c4115041",
          "md5": "136ffbc323518469cddf1cea271400df"
        }
      ]
    }
  ]
}
