{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vnpt.smartca.module.vnpt_smartca_module",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.syncfusion.flutter.pdfviewer",
          "module": "syncfusion_flutter_pdfviewer_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.deviceinfo",
          "module": "device_info_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jrai.flutter_keyboard_visibility",
          "module": "flutter_keyboard_visibility_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "appmire.be.flutterjailbreakdetection",
          "module": "flutter_jailbreak_detection_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 35629882,
          "sha512": "0b3d48d38c4013515600fc1cd7d1ad16e53f19041038825b5c1a0021d71ae3fe8a390db9039ae624ae83f7ca6fef3d1ea1e343c9195d9f1eb77d1611305d6714",
          "sha256": "1557a2ac337e1bfa844e7d5d6d4a219c22315e71ae2434caa559e80f47599bf8",
          "sha1": "86f7a36180b993383d430239fc83ef7b71d0e723",
          "md5": "e99c7bb315b2713c9947c0f4694f3f4a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.syncfusion.flutter.pdfviewer",
          "module": "syncfusion_flutter_pdfviewer_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.deviceinfo",
          "module": "device_info_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jrai.flutter_keyboard_visibility",
          "module": "flutter_keyboard_visibility_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "appmire.be.flutterjailbreakdetection",
          "module": "flutter_jailbreak_detection_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 35629882,
          "sha512": "0b3d48d38c4013515600fc1cd7d1ad16e53f19041038825b5c1a0021d71ae3fe8a390db9039ae624ae83f7ca6fef3d1ea1e343c9195d9f1eb77d1611305d6714",
          "sha256": "1557a2ac337e1bfa844e7d5d6d4a219c22315e71ae2434caa559e80f47599bf8",
          "sha1": "86f7a36180b993383d430239fc83ef7b71d0e723",
          "md5": "e99c7bb315b2713c9947c0f4694f3f4a"
        }
      ]
    }
  ]
}
