{
  "formatVersion": "1.1",
  "component": {
    "group": "com.syncfusion.flutter.pdfviewer",
    "module": "syncfusion_flutter_pdfviewer_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_profile-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_profile-1.0.aar",
          "size": 10188,
          "sha512": "b95ac0648cd23ae12d276ce14c3eaa84dbd7838829e7d7bd77592fdbd52d9f27a21fa4c4116432f3e3ef7e604f4a37e5701adbb65a749518f7c5c4dde4601bd9",
          "sha256": "f175aa158f6204d950c89bcfd415ec79f23369c95792d4a6274f4688502d6842",
          "sha1": "177103be9e22db697fb07d85ff56c0f7ed72e0d0",
          "md5": "eaba7f7b073b8e6c285a6e072e5c1a6e"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_profile-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_profile-1.0.aar",
          "size": 10188,
          "sha512": "b95ac0648cd23ae12d276ce14c3eaa84dbd7838829e7d7bd77592fdbd52d9f27a21fa4c4116432f3e3ef7e604f4a37e5701adbb65a749518f7c5c4dde4601bd9",
          "sha256": "f175aa158f6204d950c89bcfd415ec79f23369c95792d4a6274f4688502d6842",
          "sha1": "177103be9e22db697fb07d85ff56c0f7ed72e0d0",
          "md5": "eaba7f7b073b8e6c285a6e072e5c1a6e"
        }
      ]
    }
  ]
}
