{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 28750,
          "sha512": "f02490573afc9370206e7a872348e67b59a48ff5cd66a34471836d678fb190acdf00993ecfc5be0929df13bce28b8c9ed11359a418dd9775d3106a91670b1c37",
          "sha256": "3898985eeb91f77bba5ffa183f3e4dd40b8577f15f77dec6c1d9a1110e18867a",
          "sha1": "59c7c7ef226e0e0a37ab3e6939863a158470b07d",
          "md5": "f6721eeff5760cdd91a2bed7d944b708"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 28750,
          "sha512": "f02490573afc9370206e7a872348e67b59a48ff5cd66a34471836d678fb190acdf00993ecfc5be0929df13bce28b8c9ed11359a418dd9775d3106a91670b1c37",
          "sha256": "3898985eeb91f77bba5ffa183f3e4dd40b8577f15f77dec6c1d9a1110e18867a",
          "sha1": "59c7c7ef226e0e0a37ab3e6939863a158470b07d",
          "md5": "f6721eeff5760cdd91a2bed7d944b708"
        }
      ]
    }
  ]
}
