{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_file_safe_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe_debug-1.0.aar",
          "url": "open_file_safe_debug-1.0.aar",
          "size": 14444,
          "sha512": "173c456b792b46206c27a45e0188971ec7fe43efd2b7df37ee0501897a876e65b7a3b7e49648c5720c953bd93d7a3d6a4ec93ae17a5d838beff05a105b14c439",
          "sha256": "b9be7557268d13e7ad01da1a8172aac22556b886cfb340992096f639e99da328",
          "sha1": "124eeb8024c6a85ce03666cb7f8aaec0a1ebb590",
          "md5": "a34fe6289bfa044a7ae20eead0784c3b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe_debug-1.0.aar",
          "url": "open_file_safe_debug-1.0.aar",
          "size": 14444,
          "sha512": "173c456b792b46206c27a45e0188971ec7fe43efd2b7df37ee0501897a876e65b7a3b7e49648c5720c953bd93d7a3d6a4ec93ae17a5d838beff05a105b14c439",
          "sha256": "b9be7557268d13e7ad01da1a8172aac22556b886cfb340992096f639e99da328",
          "sha1": "124eeb8024c6a85ce03666cb7f8aaec0a1ebb590",
          "md5": "a34fe6289bfa044a7ae20eead0784c3b"
        }
      ]
    }
  ]
}
