{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_debug-1.0.aar",
          "url": "local_auth_android_debug-1.0.aar",
          "size": 41898,
          "sha512": "2100f2167361680b70afe73a40742fd773fba871c7afc643711914a1bf62266b3923384d7f8a2cb72b6e3d961468482fc9a728f2374ab97107593ebedb19483f",
          "sha256": "8a2295e6f916b1c61d329d01cf8333ed4b66ee93e47c73c533dc2652e69d58d5",
          "sha1": "fddeda245d9178d4e07a9cf759e533d4a7cad0da",
          "md5": "703e538f8645eac83ccee4be29c73f5a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_debug-1.0.aar",
          "url": "local_auth_android_debug-1.0.aar",
          "size": 41898,
          "sha512": "2100f2167361680b70afe73a40742fd773fba871c7afc643711914a1bf62266b3923384d7f8a2cb72b6e3d961468482fc9a728f2374ab97107593ebedb19483f",
          "sha256": "8a2295e6f916b1c61d329d01cf8333ed4b66ee93e47c73c533dc2652e69d58d5",
          "sha1": "fddeda245d9178d4e07a9cf759e533d4a7cad0da",
          "md5": "703e538f8645eac83ccee4be29c73f5a"
        }
      ]
    }
  ]
}
