{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 23293,
          "sha512": "3e799ceeff6b001d81cfeb23d51fd63cf647eb652785e4cc692d4999f8e98ce38e74a9123247f79bfc3428daa5ffc7b30ce17c1b5a6943f3b3b96c388da0240d",
          "sha256": "82fe9e24d834ad6490ab6ae7d51c20998fa237b03bff2c163706b94d854cab73",
          "sha1": "ce4a0af2842705568aba01a3c52d3b2bb17a3ab4",
          "md5": "328ae133584d60d8363a6a5daacbe1bb"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 23293,
          "sha512": "3e799ceeff6b001d81cfeb23d51fd63cf647eb652785e4cc692d4999f8e98ce38e74a9123247f79bfc3428daa5ffc7b30ce17c1b5a6943f3b3b96c388da0240d",
          "sha256": "82fe9e24d834ad6490ab6ae7d51c20998fa237b03bff2c163706b94d854cab73",
          "sha1": "ce4a0af2842705568aba01a3c52d3b2bb17a3ab4",
          "md5": "328ae133584d60d8363a6a5daacbe1bb"
        }
      ]
    }
  ]
}
